using System;
using System.Collections.Generic;
using System.Text;

namespace Lethal_Battle
{
    internal class BanScraps
    {
        public static string[] getBannedScraps()
        {
            string[] bannedScraps = {
                "BOX",
                "KEY",
                "APPARATUS",
                "MAPPER",
                "MAGIC 7 BALL",
                "BIG BOLT",
                "BOTTLES",
                "CANDY",
                "CASH REGISTER",
                "CHEMICAL JUG",
                "CLOWN HORN",
                "LARGE AXLE",
                "DUST PAN",
                "EGG BEATER",
                "V-TYPE ENGINE",
                "GOLDEN CUP",
                "FANCY LAMP",
                "PAINTING",
                "PLASTIC FISH",
                "LASER POINTER",
                "GOLD BAR",
                "HAIRDRYER",
                "MAGNIFYING GLASS",
                "METAL SHEET",
                "COOKIE MOLD PAN",
                "MUG",
                "PERFUME BOTTLE",
                "OLD PHONE",
                "JAR OF PICKLES",
                "PILL BOTTLE",
                "RED SODA",
                "STEERING WHEEL",
                "TEA KETTLE",
                "TOOTHPASTE",
                "TOY CUBE",
                "HIVE",
                "RADAR-BOOSTER",
                "AMMO",
                "FLASHLIGHT",
                "LOCKPICKER",
                "WALKIE-TALKIE",
                "BELL",
                "BRUSH",
                "TEETH",
                "REMOTE",
                "FLASK",
                "WEED KILLER",
                "SOCCER BALL",
                "CONTROL PAD",
                "GARBAGE LID",
                "PLASTIC CUP",
                "TOY TRAIN",
                "ZED DOG",
                "BELT BAG",
                "EGG",
                "BOOMBOX",
                "PRO-FLASHLIGHT",
                "STUN GRENADE",
                "TZP-INHALANT",
                "RING",
                "TOY ROBOT",
                "RUBBER DUCKY",
                "SPRAY PAINT",
                "GIFT",
                "TRAGEDY",
                "WHOOPIE CUSHION",
                "TOILET PAPER",
                "CLOCK",
                "BINOCULARS",
                "AIRHORN",

                "FRIEREN",
                "CHOCOBO",
                "SODA",
                "BASICS OF ARCHITECTURE",
                "AINZ OOAL GOWN",
                "HELM OF DOMINATION",
                "THE KING",
                "HARRY MASON",
                "MYSTIC CRISTAL",
                "PUPPY SHARK",
                "RUPEE",
                "EA-NASIR STATUE",
                "MOOGLE",
                "EL GAZPACHO",
                "THE TALKING ORB",
                "SERPENT OF RONKA",
                "HEARTHSTONE CARD",
                "CROUTON",
                "BALAN STATUE",
                "SCROLL OF TOWN PORTAL",

                "BOINK",
                "EVEE",
                "CUP NOODLE",
                "MOAI",
                "BOINK",
                "FROGGY CHAIR",
                "SUPER SNEAKERS",
                "NOKIA",
                "FREDDY FAZBEAR",
            };
            return bannedScraps;
        }
    }
}
